services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shop
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    environment:
      PORT: ":8080"
      DATABASE_URL: postgres://user:pass@db:5432/shop?sslmode=disable
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/certs:/etc/nginx/certs:ro
    depends_on:
      - backend

volumes:
  pgdata:
